name: takehome-task
channels:
  - conda-forge
  - defaults
dependencies:
  - annotated-types=0.7.0
  - backports.zstd=1.3.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - catalogue=2.0.10
  - certifi=2026.1.4
  - charset-normalizer=3.4.4
  - click=8.3.1
  - cloudpathlib=0.23.0
  - cloudpickle=3.1.2
  - colorama=0.4.6
  - confection=0.1.5
  - cymem=2.0.13
  - cython-blis=1.3.3
  - jinja2=3.1.6
  - libblas=3.11.0
  - libcblas=3.11.0
  - libexpat=2.7.3
  - libffi=3.5.2
  - libhwloc=2.12.1
  - libiconv=1.18
  - liblapack=3.11.0
  - liblzma=5.8.1
  - libsqlite=3.51.1
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - llvm-openmp=21.1.8
  - markdown-it-py=4.0.0
  - markupsafe=3.0.3
  - mdurl=0.1.2
  - mkl=2025.3.0
  - murmurhash=1.0.15
  - numpy=2.2.6
  - openssl=3.6.0
  - packaging=25.0
  - phonenumbers=9.0.21
  - pip=25.3
  - preshed=3.0.12
  - pydantic=2.12.5
  - pydantic-core=2.41.5
  - pygments=2.19.2
  - pysocks=1.7.1
  - python=3.10.19
  - python_abi=3.10
  - requests=2.32.5
  - rich=14.2.0
  - setuptools=80.9.0
  - shellingham=1.5.4
  - smart-open=7.5.0
  - smart_open=7.5.0
  - spacy=3.8.11
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.5
  - srsly=2.5.2
  - tbb=2022.3.0
  - thinc=8.3.10
  - tk=8.6.13
  - tqdm=4.67.1
  - typer=0.21.0
  - typer-slim=0.21.0
  - typer-slim-standard=0.21.0
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - ujson=5.11.0
  - urllib3=2.6.2
  - wasabi=1.1.3
  - weasel=0.4.3
  - wheel=0.45.1
  - wrapt=2.0.1
  - zstd=1.5.7
  - pip:
    - argostranslate==1.10.0
    - chardet==3.0.4
    - ctranslate2==4.6.3
    - editdistpy==0.1.6
    - emoji==2.15.0
    - fast_langdetect==1.0.0
    - filelock==3.20.3
    - fsspec==2026.1.0
    - ftfy==6.3.1
    - h11==0.9.0
    - h2==3.2.0
    - hpack==3.0.0
    - hstspreload==2025.1.1
    - httpcore==0.9.1
    - httpx==0.13.3
    - hyperframe==5.2.0
    - idna==2.10
    - joblib==1.5.3
    - mpmath==1.3.0
    - networkx==3.4.2
    - pandas==2.3.3
    - protobuf==6.33.4
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - pyyaml==6.0.3
    - regex==2025.11.3
    - rfc3986==1.5.0
    - sacremoses==0.1.1
    - sentencepiece==0.2.1
    - six==1.17.0
    - sniffio==1.3.1
    - stanza==1.10.1
    - sympy==1.14.0
    - symspellpy==6.7.8
    - tomli==2.4.0
    - torch==2.9.1
    - tzdata==2025.3
    - wcwidth==0.2.14
